name: formatter-all

on:
  push:
    branches: [ main, dev ]
  pull_request:
    types: [ labeled ]

  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'format_all') }}
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3